package com.github.putyourlightson.intellijsprigsupport

object AttributeUtil {
    val attributes = arrayOf(
        // https://github.com/putyourlightson/craft-sprig/blob/develop/src/autocompletes/SprigApiAutocomplete.php
        "sprig",
        "s-action",
        "s-boost",
        "s-confirm",
        "s-disable",
        "s-disinherit",
        "s-encoding",
        "s-ext",
        "s-headers",
        "s-history",
        "s-history-elt",
        "s-include",
        "s-indicator",
        "s-listen",
        "s-method",
        "s-on",
        "s-params",
        "s-preserve",
        "s-prompt",
        "s-push-url",
        "s-replace",
        "s-replace-url",
        "s-request",
        "s-select",
        "s-select-oob",
        "s-swap",
        "s-swap-oob",
        "s-sync",
        "s-target",
        "s-trigger",
        "s-val",
        "s-validate",
        "s-vals",
    )
}